# Generated by Django 4.1.4 on 2024-01-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
